const {Router} = require('express')
const router = Router()
const {getTelegramLogin, getTelegramOtp, resendCode, serversideLogin} = require('../controller/telegramController')
const { createGroup, joinChannel, addChatUser, createChat, getAllGroups, getGroupById, getNearbyGroups, tdCreateChat, tdJoinChatRequest, tdGetNearbyGroups, tdLoginUser } = require('../controller/groupControllers')

router.post("/login", tdLoginUser)
router.post("/verifyOtp", getTelegramOtp)
router.post("/server-login", serversideLogin)
router.post("/create-group", createGroup)
router.post("/resend-otp", resendCode)
router.post("/join-channel", joinChannel)
router.post("/add-user", addChatUser)
router.post("/create-chat", createChat)
router.get("/groups", getAllGroups)
router.post("/nearby-groups", tdGetNearbyGroups)
router.get("/groups/:channelId", getGroupById)
router.post("/create-tdchat", tdCreateChat)
router.post("/join-tdchat", tdJoinChatRequest)

module.exports = router;